---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: 0644

    - name: Add Docker repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable'
        create: yes
        owner: root
        group: root
        mode: '0644'

    - name: Update apt repository
      shell: |
        sudo apt update
        sudo apt-cache policy docker-ce

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
