---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      shell: |
        sudo apt-update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common -y


    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
