---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      shell: |
        sudo apt-update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common -y


    - name: Download Docker GPG key
      shell: |
        sudo gpg --recv-keys --keyserver keyserver.ubuntu.com 7EA0A9C3F273FCD8
        sudo gpg --export --output /usr/share/keyrings/docker-archive-keyring.gpg
        sudo apt update
        sudo apt-cache policy docker-ce

    - name: Install Docker
      shell: |
        sudo apt install docker-ce
        sudo systemctl status docker

    
    - name: Add username to the docker group
      command: sudo usermod -aG docker ${USER}

    
    - name: Docker info
      command: docker info
      register: result

    - debug: 
        var: result
